---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1  # Set replicas to 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: manuhubumb/movieticket:latest  
          ports:
            - containerPort: 1234  # Adjust to your backend port
          env:
            - name: DATABASE_URL
              value: "url=jdbc:mysql://root:Rootadmin1234@autorack.proxy.rlwy.net:13077/railway"  # Update your DB config
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # Adjust as necessary

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "httpalb" 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 1234  # Adjust to your backend port
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1  # Set replicas to 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: manuhubumb/movieticket:latest  # Replace with your frontend image
          ports:
            - containerPort: 80  # Adjust to your frontend port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80  # Adjust to your frontend port
  selector:
    app: frontend
